### ISSUE TITLE
Give credit to original author

### ISSUE THREAD

**Issue by safinsingh** [simarpreetsingh-019/Typing-speed-Tester#1]
Give credit to original author of program at: https://gist.github.com/Rockrdx710/921b213e7d1c1e6b688e400c80cf8a71

**Comment by simarpreetsingh-019** [comment]
Hey @safinsingh , thanks for reaching out here.
Sorry but I don't even knew that you have made this same thing 7 months ago, I just made it after seeing a video tutorial from an Instagram page name code_cravings. I talked to him, he had no problem that I haven't specifically tagged him. But made iy=t with help from his repo and video. 
Sorry .
